@@include('../component/dinamicAdaptiv/js/dinamicAdaptiv.js')
@@include('../component/lazyLoad/js/lazyLoad.js')
@@include('../component/Tabs/js/tabs.js')
@@include('files/sliders/createSliders.js')
@@include('libs/nouislider.js')
@@include('libs/wNumb.min.js')
